version: '3'

services:
  web:
    build: .
    volumes:
     - .:/holistic-backend
    ports:
     - 8080:8080
    links:
      - postgres:postgres
    depends_on:
      - postgres
    env_file:
      - .env.example

  postgres:
    image: postgres:13-alpine
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: always
    env_file:
      - .env.example
