# Generated by Django 3.2.16 on 2022-12-21 04:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=128, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TherapistOrganization',
            fields=[
                ('id', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('date_joined', models.DateField()),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='holistic_organization.organization')),
            ],
            options={
                'unique_together': {('id', 'organization')},
            },
        ),
        migrations.CreateModel(
            name='TherapistInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interaction_id', models.PositiveIntegerField()),
                ('chat_count', models.PositiveIntegerField()),
                ('call_count', models.PositiveIntegerField()),
                ('interaction_date', models.DateField()),
                ('therapist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='holistic_organization.therapistorganization')),
            ],
            options={
                'unique_together': {('therapist', 'interaction_date', 'interaction_id')},
            },
        ),
    ]
