# Generated by Django 3.2.16 on 2022-11-16 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=128, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TherapistInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('therapist_id', models.CharField(max_length=32)),
                ('interaction_date', models.DateField()),
                ('chat_count', models.PositiveIntegerField()),
                ('call_count', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TherapistOrganization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('therapist_id', models.CharField(max_length=32)),
                ('date_joined', models.DateField()),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='holistic_organization.organization')),
            ],
            options={
                'unique_together': {('organization', 'therapist_id')},
            },
        ),
    ]
