# Generated by Django 3.2.16 on 2022-12-21 05:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('holistic_organization', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='therapistorganization',
            name='date_joined',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='therapistorganization',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='holistic_organization.organization'),
        ),
    ]
