# Generated by Django 3.2.16 on 2022-12-07 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('holistic_organization', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='therapistinteraction',
            index=models.Index(fields=['id', 'therapist_id'], name='ti_id_therapist_id_idx'),
        ),
        migrations.AddIndex(
            model_name='therapistinteraction',
            index=models.Index(fields=['therapist_id', 'interaction_date'], name='ti_therapist_id_interaction_date_idx'),
        ),
        migrations.AddIndex(
            model_name='therapistorganization',
            index=models.Index(fields=['organization_id', 'therapist_id'], name='to_organization_id_therapist_id_idx'),
        ),
    ]
