# Generated by Django 3.2.16 on 2022-11-18 08:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('holistic_organization', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NumberOfTherapist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_active', models.BooleanField(default=False)),
                ('value', models.PositiveIntegerField()),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='holistic_organization.organization')),
            ],
        ),
        migrations.CreateModel(
            name='ChurnRetentionRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('type', models.CharField(choices=[('churn_rate', 'Churn Rate'), ('retention_rate', 'Retention Rate')], max_length=16)),
                ('rate_value', models.FloatField()),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='holistic_organization.organization')),
            ],
        ),
    ]
