# Generated by Django 3.2.16 on 2022-12-22 09:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('holistic_organization', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('churn_rate', 'Churn Rate'), ('retention_rate', 'Retention Rate')], max_length=16)),
                ('period_type', models.CharField(choices=[('weekly', 'Weekly'), ('monthly', 'Monthly'), ('yearly', 'Yearly')], max_length=8)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('rate_value', models.FloatField()),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='holistic_organization.organization')),
            ],
            options={
                'unique_together': {('organization', 'type', 'start_date', 'end_date', 'period_type')},
            },
        ),
        migrations.CreateModel(
            name='NumberOfTherapist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_type', models.CharField(choices=[('weekly', 'Weekly'), ('monthly', 'Monthly'), ('yearly', 'Yearly')], max_length=8)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_active', models.BooleanField(default=False)),
                ('value', models.PositiveIntegerField()),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='holistic_organization.organization')),
            ],
            options={
                'unique_together': {('organization', 'start_date', 'end_date', 'period_type', 'is_active')},
            },
        ),
    ]
