# Generated by Django 3.2.16 on 2022-12-28 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('holistic_data_presentation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllTimeOrganizationRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('type', models.CharField(choices=[('churn_rate', 'Churn Rate'), ('retention_rate', 'Retention Rate')], max_length=16)),
                ('rate_value', models.FloatField()),
            ],
            options={
                'unique_together': {('start_date', 'end_date', 'type')},
            },
        ),
        migrations.CreateModel(
            name='AllTimeNumberOfTherapist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_active', models.BooleanField(default=False)),
                ('value', models.PositiveIntegerField()),
            ],
            options={
                'unique_together': {('start_date', 'end_date', 'is_active')},
            },
        ),
    ]
