# Generated by Django 3.2.16 on 2022-12-28 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('holistic_data_presentation', '0002_alltimenumberoftherapist_alltimeorganizationrate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alltimenumberoftherapist',
            name='is_active',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='alltimeorganizationrate',
            name='type',
            field=models.CharField(blank=True, choices=[('churn_rate', 'Churn Rate'), ('retention_rate', 'Retention Rate')], max_length=16),
        ),
    ]
